#!/usr/bin/env bash
# displays Best school School 10 times.

expr=0
while [ $expr -lt 11 ]
do
    if [ $expr = 9 ]
        then
      echo "Hi"
    else
     echo "Best School"
     fi
    (( expr++ ))
done
